version: "3"

services:
  auth:
    image: auth
    build: ./auth
    command: apistar run --port 80 --host 0.0.0.0
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/auth/*"
      VIRTUAL_HOST_WEIGHT: 10
    volumes:
      - ./auth:/code

  service:
    image: service
    build: ./service
    command: apistar run --port 80 --host 0.0.0.0
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/service/*"
      VIRTUAL_HOST_WEIGHT: 10
    volumes:
      - ./service:/code
  
  ui:
    image: ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - 3000
    environment:
      VIRTUAL_HOST: "*/*"
      SERVICE_PORTS: 3000
      VIRTUAL_HOST_WEIGHT: 0
    volumes:
      - ./ui:/app

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '1936:1936'
    links:
      - auth
      - service
      - ui