version: "3"

services:
  auth:
    image: auth
    build: ./auth
    command: apistar run --port 80 --host 0.0.0.0
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/auth/*"
      VIRTUAL_HOST_WEIGHT: 10

  service:
    image: service
    build: ./service
    command: apistar run --port 80 --host 0.0.0.0
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/service/*"
      VIRTUAL_HOST_WEIGHT: 10
  
  ui:
    image: ui
    build: ./ui
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/*"
      VIRTUAL_HOST_WEIGHT: 0

  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '1936:1936'
    links:
      - auth
      - service
      - ui